version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: streaming_db
    environment:
      POSTGRES_USER: streaming_user
      POSTGRES_PASSWORD: streaming_pass
      POSTGRES_DB: streaming_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: